# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-dfe56e85-7a72-4439-a894-506d2666f3b2";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."luks-dfe56e85-7a72-4439-a894-506d2666f3b2".device = "/dev/disk/by-uuid/dfe56e85-7a72-4439-a894-506d2666f3b2";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/EB56-3AC4";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/mapper/luks-459598c4-170f-4f17-bcc3-42df0ddb6174";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-459598c4-170f-4f17-bcc3-42df0ddb6174".device = "/dev/disk/by-uuid/459598c4-170f-4f17-bcc3-42df0ddb6174";

  swapDevices =
    [ { device = "/dev/mapper/luks-c8724694-43ff-4c8d-9f30-c09fd2e85503"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
