device.profile.priority.rules = [
  {
    matches = [
      {
        device.name = "~alsa_card.*"
      }
    ]
    actions = {
      update-props = {
        priorities = [
          "output:analog-stereo+input:analog-stereo"
          "output:analog-stereo"
        ]
      }
    }
  }
]
