$primary = rgb(e6a6c8)
$surface = rgb(10111b)
$secondary = rgb(afa2d8)
$error = rgb(f08a9b)
$tertiary = rgb(7fb6d6)
$surface_lowest = rgb(12121e)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
